server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://dpg-d811r0u7r5hc73c3h6ig-a.oregon-postgres.render.com:5432/buss_cdlh
    username: mediconnect_user
    password: Qgak155683CuJItyT54nXIC7wG0hBFnO
  jpa:
    hibernate:
      ddl-auto: update   # create, create-drop, update, validate, none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8081/.well-known/jwks.json
    uri: http://localhost:8081

  uri-front: "http://localhost:3000"

api:
  auth:
    uri: "http://localhost:8081"