server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://44.212.161.13:5432/mediconnect_db
    username: postgres
    password: wBtChxKHNsK6xvTsJeQSdKSLae8agNAiO
  jpa:
    hibernate:
      ddl-auto: update   # create, create-drop, update, validate, none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://44.212.161.13:8081/.well-known/jwks.json
    uri: http://44.212.161.13:8081

  uri-front: "http://44.212.161.13:3000"

api:
  auth:
    uri: "http://44.212.161.13:8081"